class StubLLMAdapter:
    model_name = "stub-llm-v1"

    def generate(self, prompt: str) -> str:
        title = "Backtest Analysis Report"
        findings = [
            "The system successfully completed a backtest.",
            "Metrics were converted into a natural-language summary.",
            "This layer can later be replaced by a real LLM provider.",
        ]
        suggestions = [
            "Add richer metrics.",
            "Add drawdown window analysis.",
            "Add structured JSON output for dashboard cards.",
        ]

        lowered = prompt.lower()
        if "diagnos" in lowered:
            title = "Backtest Result Diagnosis"
            findings = [
                "Drawdown risk should be reviewed against target risk tolerance.",
                "Trade frequency should be checked for possible overtrading.",
                "Returns should be inspected for concentration in short favorable windows.",
            ]
            suggestions = [
                "Review drawdown windows and loss clustering.",
                "Measure trades per month and average holding period.",
                "Compare performance stability across time segments.",
            ]

        return f"""
# {title}

## Executive Summary
This report is generated by the stub LLM adapter.

## Key Findings
- {findings[0]}
- {findings[1]}
- {findings[2]}

## Prompt Snapshot
{prompt[:1200]}

## Suggestions
- {suggestions[0]}
- {suggestions[1]}
- {suggestions[2]}
""".strip()


class OpenAIAdapter:
    def __init__(self, client, model_name: str):
        self.client = client
        self.model_name = model_name

    def generate(self, prompt: str) -> str:
        resp = self.client.responses.create(
            model=self.model_name,
            input=prompt,
        )
        return resp.output_text
