# Generated by Django 5.0.8 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_task_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("GENERATE_REPORT", "Generate Report"),
                            ("EXPLAIN_BACKTEST", "Explain Backtest"),
                            ("DIAGNOSE_RESULT", "Diagnose Result"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("FORECAST", "Forecast"), ("BACKTEST", "Backtest")],
                        max_length=32,
                    ),
                ),
                ("source_id", models.CharField(max_length=64)),
                ("input_refs_json", models.JSONField(default=dict)),
                ("prompt_template_version", models.CharField(default="v1", max_length=32)),
                ("model_name", models.CharField(default="stub-llm-v1", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("output_uri", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("FORECAST", "Forecast"), ("BACKTEST", "Backtest")],
                        max_length=32,
                    ),
                ),
                ("source_id", models.CharField(max_length=64)),
                ("llm_task_id", models.CharField(db_index=True, max_length=64)),
                ("title", models.CharField(max_length=200)),
                (
                    "format",
                    models.CharField(
                        choices=[("MARKDOWN", "Markdown"), ("JSON", "Json")],
                        max_length=16,
                    ),
                ),
                ("uri", models.TextField()),
                ("summary_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
