# Generated by Django 5.0.8 on 2026-02-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForecastJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_job_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("model_type", models.CharField(max_length=64)),
                ("params_json", models.JSONField(default=dict)),
                ("horizon", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("output_uri", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="forecastjob",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "idempotency_key"), name="uq_tenant_idem_key"
            ),
        ),
    ]
