# Generated by Django 5.0.8 on 2026-02-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastjob",
            name="dedup_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
