# Generated by Django 5.0.8 on 2026-02-22 03:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0004_forecastjob_dataset_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_id",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("tenant_id", models.CharField(max_length=64)),
                ("base_currency", models.CharField(default="USD", max_length=16)),
                ("initial_cash", models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy_id",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("tenant_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("type", models.CharField(max_length=32)),
                ("spec_json", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SignalRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signal_run_id",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("tenant_id", models.CharField(max_length=64)),
                ("forecast_job_id", models.CharField(max_length=128)),
                ("status", models.CharField(default="PENDING", max_length=32)),
                ("output_uri", models.CharField(blank=True, max_length=512, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forecasting.strategy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TradeSimRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade_sim_run_id",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("tenant_id", models.CharField(max_length=64)),
                (
                    "execution_model",
                    models.CharField(default="NEXT_BAR_CLOSE", max_length=32),
                ),
                ("status", models.CharField(default="PENDING", max_length=32)),
                ("output_uri", models.CharField(blank=True, max_length=512, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forecasting.simaccount",
                    ),
                ),
                (
                    "signal_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forecasting.signalrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
