# Generated by Django 5.0.8 on 2026-03-02 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasting", "0005_simaccount_strategy_signalrun_tradesimrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("source_type", models.CharField(max_length=32)),
                ("source_id", models.CharField(max_length=64)),
                ("format", models.CharField(default="MARKDOWN", max_length=32)),
                ("uri", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backtest_run_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("tenant_id", models.CharField(db_index=True, max_length=64)),
                ("forecast_config_snapshot_json", models.JSONField(default=dict)),
                ("account_config_json", models.JSONField(default=dict)),
                ("execution_config_json", models.JSONField(default=dict)),
                ("risk_rules_json", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("FORECAST_PENDING", "Forecast Pending"),
                            ("FORECAST_DONE", "Forecast Done"),
                            ("SIGNAL_PENDING", "Signal Pending"),
                            ("SIGNAL_DONE", "Signal Done"),
                            ("SIM_PENDING", "Sim Pending"),
                            ("SIM_DONE", "Sim Done"),
                            ("METRICS_DONE", "Metrics Done"),
                            ("REPORT_DONE", "Report Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="CREATED",
                        max_length=32,
                    ),
                ),
                (
                    "forecast_job_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "signal_run_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "trade_sim_run_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("metrics_json", models.JSONField(default=dict)),
                ("output_uri", models.TextField(blank=True, null=True)),
                ("report_uri", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dataset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forecasting.datasetversion",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forecasting.strategy",
                    ),
                ),
            ],
        ),
    ]
